apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-showcase
  title: Backstage Showcase
  description: |
    This is a showcase of Red Hat Developer Hub Showcase, base on the Janus Showcase of Backstage.io
  links:
    - title: Janus Website
      url: https://janus-idp.io
    - title: Janus Showcase
      url: https://showcase.janus-idp.io/
    - title: Blog
      url: https://janus-idp.io/blog
    - title: Slack - Janus
      url: https://join.slack.com/t/janus-idp/shared_invite/zt-1pxtehxom-fCFtF9rRe3vFqUiFFeAkmg
  annotations:
    argocd/app-name: 'backstage-showcase-dev'
    backstage.io/kubernetes-id: 'backstage-showcase'
    github.com/project-slug: idp-myocp/backstage-showcase
    backstage.io/techdocs-ref: url:https://github.com/idp-myocp/backstage-showcase
    backstage.io/kubernetes-namespace: developer-hub
    sonarqube.org/project-key: backstage-showcase
    jfrog-artifactory/image-name: backstage-showcase

spec:
  type: website
  system: janus-idp
  owner: janus-authors
  lifecycle: production
  dependsOn:
    - resource:pgdb
    - resource:argocd
    - resource:obc
    - resource:keycloak
    - resource:github